
export const appPaths = {
  login: '/login',
  home: '/home',
  main: '/main',
  document: '/document',
  application: '/application',
  profile: '/profile',
  wallet: '/wallet',
  setting: '/setting',
  dashboard: '/dashboard',
  service: '/service',
  career: '/career',
  personal: '/personal',
  med: '/med',
  vacation: '/vacation',
  incentive: '/incentive',
  punishment: '/punishment',
  relative: '/relative',
}
